# This is a basic workflow to help you get started with Actions

name: Covid NYS Monitor

on:
  schedule:
  - cron: "*/20 * * * *"
  workflow_dispatch:
  push:
    branches: [ master ]

defaults:
    run:
       shell: bash
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #  setup node dependencies
      - run: npm ci
      - name: firebaseConfig
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo "${FIREBASE_CONFIG}" > .firebaseConfig.json
     
      - run: node fetch_nys_covid.js
        env:
          MAILER_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
