# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish To GH Pages

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Los_Angeles
    - name: firebaseConfig
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: cd website; echo "${FIREBASE_CONFIG}" > ./src/firebaseConfig.json;  cd ..
    # - run: git submodule init ;  git submodule update 
    # - run: pushd covid-19-data; git checkout master; git pull; popd
    - run: tail covid-19-data/us-counties.csv 
    - name: Google project credentials
      env:
        GOOGLE_SVC_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SVC_ACCOUNT_CREDENTIALS }}
      run: echo "${GOOGLE_SVC_ACCOUNT_CREDENTIALS}" > /tmp/.googleCredentials.json
    - run: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y xmlstarlet
    - run: npm ci
    - run: cd website; npm ci  ; cd ..
    - run: cd website; npm run build --if-present; cd ..
    - run: cd website; echo "gowatchit.net" > build/CNAME; cd ..
    - run: mkdir -p website/build/data/vaccine/counties website/build/data/testing
    - run: node ts-out/dataget.js -t "RandomDataTables/CDC-National-Vaccination-Trends/DataRecords" > website/build/data/vaccine/USA.CDC.json
    - run : cat website/build/data/vaccine/USA.CDC.json | jq  '[ .vaccination_trends_data | .[] |select (.Location=="US") | select (.date_type == "Admin")  ] |sort_by(.Date)' > website/build/data/vaccine/USA.json
    - run: node ts-out/dataget.js -t CDC-Vaccine-Overtime-Table  > website/build/data/vaccine/states.json
    - run: node ts-out/datasplit.js -t CDC-Vaccine-Overtime-Table -f Location -o website/build/data/vaccine
    - name: fetch data
      env:
          MAILGUN_TOKEN: ${{ secrets.MAILGUN_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/.googleCredentials.json
      run: sh -vxe datagen.sh
    - run: cat website/build/data/county-details/06001.json  |jq
    - name: Deploy to Website
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: website/build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
